### ISSUE TITLE
One ActiveMQ connection is down from the beginning, another one is running.

### ISSUE THREAD

**Issue by debmalya** [debmalya/ActiveMqStaleConnectionHandler#2]
java.lang.NullPointerException
	at com.example.JMSLoadBalancerSink.reconnect(JMSLoadBalancerSink.java:337)
	at com.example.JMSLoadBalancerSink.access$1(JMSLoadBalancerSink.java:324)
	at com.example.JMSLoadBalancerSink$Recoverer.run(JMSLoadBalancerSink.java:470)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by debmalya** [comment]
Fix for this issue
ActiveMQConnectionFactory connectionFactory = connectionFactoryList.get(i);
					if (connectionFactory == null) {
						connectionFactory = new ActiveMQConnectionFactory(brokerURL[i]);
					}
					if (connectionFactory != null) {

						// Fix for issue #2
						connectionFactoryList.set(i, connectionFactory);
						Connection connection = connectionFactory.createConnection();
                                                 ....
                                        }
